version: "3.5"
services:
  postgresql:
    container_name: temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:${POSTGRESQL_VERSION:-17.5}
    networks:
      - temporal-network
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  temporal:
    container_name: temporal
    depends_on:
      - postgresql
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
      - LOG_LEVEL=info
    image: temporalio/auto-setup:${TEMPORAL_VERSION:-1.28}
    networks:
      - temporal-network
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
    healthcheck:
      test: ["CMD", "temporal", "operator", "cluster", "health", "--address", "temporal:7233"]
      interval: 2s
      timeout: 10s
      retries: 30
  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:${TEMPORAL_ADMINTOOLS_VERSION:-1.28}
    networks:
      - temporal-network
    # stdin_open: true
    # tty: true
  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:${TEMPORAL_UI_VERSION:-2.39.0}
    networks:
      - temporal-network
    ports:
      - 8080:8080
  worker:
    build:
      context: .
    command: "temporal:run_worker['temporal:7233','default']"
    scale: 2
    depends_on:
      temporal:
        condition: service_healthy
    environment:
      - "TEMPORAL_ADDRESS=temporal:7233"
      - "TEMPORAL_NAMESPACE=default"
      - "LOG_LEVEL=debug"
    networks:
      - temporal-network
    volumes:
      - ./:/app
networks:
  temporal-network:
    driver: bridge
    name: temporal-network
